# Generated by Django 5.2 on 2025-04-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Glucose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("timestamp", models.DateTimeField()),
                ("record_type", models.IntegerField()),
                ("glucose_value_trend", models.IntegerField(blank=True, null=True)),
                ("glucose_scan", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
